//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        public string НомерАвто { get; set; }
        public string Марка { get; set; }
        public string Модель { get; set; }
        public string Цвет { get; set; }
        public Nullable<int> ГодВыпуска { get; set; }
        public Nullable<System.DateTime> ДатаРегистрации { get; set; }
        public string Владелец { get; set; }
    
        public virtual Водители Водители { get; set; }
    }
}
