//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class НарушенияПДД
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public НарушенияПДД()
        {
            this.Взыскания = new HashSet<Взыскания>();
            this.НарушенияВодителей = new HashSet<НарушенияВодителей>();
        }
    
        public int КодНарушения { get; set; }
        public string ВидНарушения { get; set; }
        public string ШтрафДиапазон { get; set; }
        public Nullable<bool> Предупреждение { get; set; }
        public Nullable<int> СрокЛишенияПрав { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Взыскания> Взыскания { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<НарушенияВодителей> НарушенияВодителей { get; set; }
    }
}
