//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class НарушенияВодителей
    {
        public int КодНарушения { get; set; }
        public string НомерВУ { get; set; }
        public Nullable<System.DateTime> ДатаВремяНарушения { get; set; }
        public string РайонНарушения { get; set; }
    
        public virtual Водители Водители { get; set; }
        public virtual НарушенияПДД НарушенияПДД { get; set; }
    }
}
